//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated by the MSBuild CreateWin32MetadataFile target.

namespace WebView2Aot.InteropBuilder.Cli
{
    public static class Win32Metadata
    {
        public const string WinMdPath = @"d:\Github\WebView2Aot\WebView2Aot.InteropBuilder.Cli\";
        public const string SolutionDir = @"*Undefined*";
    }
}
